# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the trunk branch
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    name: Pylint
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint black
        pip install --requirement requirements.txt
        
    - name: Analysing the code with pylint
      run: |
        if [ -f *.py ]; then
          black `ls -R *.py|xargs`
          pylint `ls -R *.py|xargs`
        fi
#          pylint `ls -R|grep .py$|xargs`

  deploy:
    runs-on: ubuntu-20.04
    needs: build
    steps:
    - name: Deta
      run: pip install deta
    - name: Deploy
      run: echo ${{needs.build.outputs}}
