name: Pylint

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint black
        pip install --requirement requirements.txt
        
    - name: Analysing the code with pylint
      run: |
        if [ -f *.py ]; then
          black `ls -R *.py|xargs`
          pylint `ls -R *.py|xargs`
        fi
#          pylint `ls -R|grep .py$|xargs`

