name: Pylint

on: [push]

jobs:
  build:

    runs-on: debian-10

    steps:
    - uses: actions/checkout
    - name: Set up Python 3.7
      uses: actions/setup-python
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint black
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
